image: python:3.9.7
stages:
  - ver
  - init
  - staging
ver:
  stage: ver
  script:
    - python --version
    - whoami
init:
  stage: init
  script:
    - apt-get update -qy
    - pip install -r requirements.txt

deploy_staging:
  stage: staging
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=third3ye --api-key=49a70c16-4f8d-4018-b49b-6b6d8293446a
